### ISSUE TITLE
Switch for glyph coords

### ISSUE THREAD

**Issue by wpmp** [inception-project/pdfextract#5]
The output of PDFExtract always shows font coordinates and glyph coordinates.
A possibility to switch glyph coordinates on/off is added to PDFExtract.

**Comment by reckart** [comment]
What is the benefit of being able to turn them on/off?

**Comment by wpmp** [comment]
PDFAnno uses output of PDFExtract 0.3.0.
In this version there was the possibility to turn them on/off.
In 0.3.1 the option is gone.
PDFAnno consumes output without glyph coordinates.
I found out earlier this day that when PDFAnno receives both coordinates it can't handle it properly and I am not able to select any text.
When I remove glyph coordinates from output it works fine and I can select text and create annotations.

I would only add a boolean to PDFExtractor and provide its value over the constructor.
The boolean then determines if the glyph output is written to the writer or not.
I would only change my new method from #3 and let the existing method, that produces a file as output, to still produce glyph coordinates.

**Comment by reckart** [comment]
In order to minimize the impact on the API  - in particular if you plan to turn this into another PR - I would recommend creating a getter/setter to set this flag instead of passing it to the constructor.

**Comment by wpmp** [comment]
Ok I will do it this way!
